### ISSUE TITLE
Unable to run on Manjaro

### ISSUE THREAD

**Issue by AllenDazi** [nagadomi/waifu2x#342]
Hello, I followed the steps in README.md but it can't work. I tried reinstalling it (including rninstalling torch) multiple times. But if I run the lua file, it kept reporting this error:

> THCudaCheck FAIL file=/home/dazian/wf2x/torch/extra/cutorch/lib/THC/generic/THCTensorMath.cu line=15 error=8 : invalid device function
> /home/dazian/wf2x/torch/install/bin/luajit: ...dazian/wf2x/torch/install/share/lua/5.1/nn/Container.lua:67: 
> In 1 module of nn.Sequential:
> In 1 module of nn.Sequential:
> In 1 module of nn.Sequential:
> /home/dazian/wf2x/torch/install/share/lua/5.1/nn/THNN.lua:110: cuda runtime error (8) : invalid device function at /home/dazian/wf2x/torch/extra/cutorch/lib/THC/generic/THCTensorMath.cu:15
> stack traceback:
>         [C]: in function 'v'
>         /home/dazian/wf2x/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialConvolutionMM_updateOutput'
>         .../torch/install/share/lua/5.1/nn/SpatialConvolutionMM.lua:63: in function <.../torch/install/share/lua/5.1/nn/SpatialConvolutionMM.lua:53>
>         [C]: in function 'xpcall'
>         ...dazian/wf2x/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
>         ...azian/wf2x/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function <...azian/wf2x/torch/install/share/lua/5.1/nn/Sequential.lua:41>
>         [C]: in function 'xpcall'
>         ...dazian/wf2x/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
>         ...azian/wf2x/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function <...azian/wf2x/torch/install/share/lua/5.1/nn/Sequential.lua:41>
>         [C]: in function 'xpcall'
>         ...dazian/wf2x/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
>         ...azian/wf2x/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
>         lib/reconstruct.lua:52: in function 'reconstruct_nn'
>         lib/reconstruct.lua:200: in function 'scale_rgb'
>         lib/reconstruct.lua:240: in function 'scale_f'
>         waifu2x.lua:99: in function 'convert_image'
>         waifu2x.lua:294: in function 'waifu2x'
>         waifu2x.lua:299: in main chunk
>         [C]: in function 'dofile'
>         ...wf2x/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
>         [C]: at 0x004060c0

I tried force_cudnn argument, it doesn't work, and kept reporting errors above.
nvidia_smi report:

>  | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |   0  GeForce GTX 1660    Off  | 00000000:01:00.0  On |                  N/A |
> | 25%   34C    P8     6W / 120W |    451MiB /  5941MiB |      4%      Default |

**Comment by nagadomi** [comment]
Is that Torch7 my distro repository( https://github.com/nagadomi/distro ) built with CUDA10?
NVIDIA Turing is a new architecture and is not supported by the official Torch7 and older CUDA versions.

**Comment by AllenDazi** [comment]
OK, I solved it and it seems to be working just fine. Thank you for your help.
